// ---------------------------------------------------------------------------
// Seed brand profiles.
//
// These lived in src/App.jsx, which meant they shipped inside the public JS
// bundle - and /assets/* is served without a session so the login screen can
// load. That put our own written commentary on thirteen named clients (their
// ICP, offers, objections, compliance risks, and the gaps we hadn't confirmed)
// on a URL anyone could fetch.
//
// They are served from the settings endpoint instead, to staff only. A saved
// profile always overrides its seed.
// ---------------------------------------------------------------------------
export const CLIENT_PROFILE_SEEDS = {
  'pool-haus': { oneLiner: 'Premium custom concrete (inground) pool builder', industry: 'Home improvement - swimming pool construction', voice: 'Confident, premium and reassuring; plain-English; aspirational lifestyle backed by builder credibility', icp: 'Homeowners (mainly Sydney + Central Coast) wanting a custom inground concrete pool; renovators and new-build owners who value quality and a trustworthy builder over the cheapest quote', offer: 'Custom concrete pool design and construction. [Confirm exact inclusions, price range, finance options and warranty]', differentiators: '[Confirm - e.g. in-house build team, fixed-price contract, design service, workmanship warranty]', objections: 'Cost, disruption / mess, how long it takes, trusting the builder to finish well, ongoing maintenance', proof: '[Add real proof: number of pools built, review rating, awards, warranty length]', keywords: 'concrete pool, inground pool, custom pool, pool builder Sydney, backyard transformation, plunge pool', adNotes: 'Before/after backyard transformations, build-process demos, finished-pool lifestyle, warranty & quality reassurance. Angles: aspiration + trust.', notes: 'Sydney + Central Coast. Runs Meta lead forms and website-conversion campaigns.' },
  'nexia-health': { oneLiner: 'Mental health and allied health care provider', industry: 'Healthcare - mental health & allied health', voice: 'Warm, empathetic, professional and reassuring; non-judgemental; clear and accessible', icp: 'People seeking mental health / allied health support and their families; self-referred or GP-referred; want to feel understood and get timely, quality care', offer: 'Mental health and allied health services. [Confirm disciplines (psychology, counselling, OT, etc.), telehealth vs in-person, and funding: Medicare / NDIS / private]', differentiators: '[Confirm - e.g. multidisciplinary team, short wait times, funding pathways, telehealth]', objections: 'Cost / funding, stigma, wait times, whether it will help, finding the right clinician', proof: '[Add real proof: clinician credentials, accreditations, privacy-safe outcomes]', keywords: 'mental health support, psychology, counselling, allied health, telehealth', avoidWords: 'Keep AHPRA-compliant: no outcome guarantees and no prohibited testimonials', adNotes: 'Empathy-led and educational; gentle book/enquire CTA. Health-advertising compliance matters.', notes: 'Health advertising: follow AHPRA rules (no prohibited testimonials, no outcome claims).' },
  'finr-advisory': { oneLiner: 'Property-investment finance advisory + buyer’s advocacy', industry: 'Finance - mortgage broking / property investment advisory', voice: 'Credible, educational and confident; numbers-led but jargon-free; wealth-building aspiration with trust', icp: 'Everyday investors and “rentvestors” wanting to buy investment property, lift borrowing capacity, or use equity / CGT strategies; time-poor professionals who want expert guidance', offer: 'Borrowing-capacity and finance advice plus buyer’s advocacy for property investors. [Confirm services, fees and states served]', differentiators: '[Confirm - e.g. combined finance + buyer’s agent, data-led property selection, end-to-end service]', objections: 'Trusting someone with money, fees, market timing / risk, borrowing capacity, “is now a good time”', proof: '[Add real proof: clients helped, properties settled, credit licence / credentials, reviews]', keywords: 'borrowing capacity, investment property, rentvesting, capital gains, buyers agent, property investment, equity', avoidWords: 'Avoid guaranteed-return or personal financial-advice claims; include appropriate credit / finance disclaimers', adNotes: 'Podcast-style education + case studies (e.g. Melbourne rentvestors, CGT, new builds). Two pipelines: FINR Advisory (finance) and Buyers Advocacy.', notes: 'Runs [FIN] FINR Advisory and [BA] Buyers Advocacy pipelines. Finance-advertising compliance applies.' },
  'psychology-hub': { oneLiner: 'Psychology practice', industry: 'Healthcare - psychology / mental health', voice: 'Warm, professional, reassuring and non-judgemental', icp: 'Adults, teens and parents seeking psychology support; self-referred or GP-referred', offer: 'Psychology and counselling services. [Confirm telehealth vs in-person, Medicare rebates, specialties]', objections: 'Cost / rebates, stigma, wait times, finding the right psychologist', proof: '[Add credentials, Medicare provider status, accreditations]', keywords: 'psychologist, counselling, therapy, mental health, Medicare rebate', avoidWords: 'AHPRA-compliant: no outcome guarantees or prohibited testimonials', adNotes: 'Empathy + education; gentle booking CTA.', notes: 'Health advertising compliance (AHPRA).' },
  'book-a-midwife': { oneLiner: 'Private midwifery and maternity care', industry: 'Healthcare - midwifery / maternity', voice: 'Warm, nurturing, empowering and professional', icp: 'Expecting parents wanting personalised private midwifery care and continuity of carer', offer: 'Private midwife booking and maternity care. [Confirm: home birth / hospital, antenatal / postnatal, Medicare, service areas]', objections: 'Cost / Medicare, safety, availability, how it works alongside the hospital', proof: '[Add midwife credentials, births supported, reviews]', keywords: 'private midwife, continuity of care, home birth, antenatal, postnatal, maternity care', avoidWords: 'Health-advertising compliant; no birth-outcome guarantees', adNotes: 'Story and empowerment-led; educate on continuity of care; gentle enquiry CTA.' },
  'rlm-telehealth': { oneLiner: 'Telehealth service', industry: 'Healthcare - telehealth', voice: 'Accessible, convenient, professional and reassuring', icp: 'People wanting convenient remote access to health consults [confirm specialty]', offer: 'Telehealth consultations. [Confirm services / specialty, funding, booking]', objections: 'Is telehealth as good as in-person, cost / rebates, technology, privacy', keywords: 'telehealth, online consult, remote appointment', avoidWords: 'Health-advertising compliant', adNotes: 'Convenience + access angle; educational.', notes: '[Confirm the specialty / services RLM Telehealth provides.]' },
  'swift-emergency': { oneLiner: 'Rapid emergency-response service', industry: 'Emergency services / trades [confirm exact type]', voice: 'Urgent, reassuring, reliable and fast', icp: 'People with an urgent problem who need fast, trustworthy help right now', offer: 'Rapid emergency response. [Confirm exact service (plumbing / electrical / restoration / other), 24-7 availability, areas, pricing]', objections: 'Response time, call-out cost, trust, availability', keywords: 'emergency, 24/7, fast response, urgent', adNotes: 'Urgency + reliability (“we’re there fast”); call / enquiry CTA.', notes: '[Confirm exactly what emergency service Swift provides.]' },
  'healan-centre': { oneLiner: 'Allied health / wellness centre [confirm]', industry: 'Healthcare - allied health [confirm]', voice: 'Caring, professional and reassuring', icp: '[Confirm target patients]', offer: '[Confirm services offered]', avoidWords: 'If health services, keep AHPRA-compliant', notes: '[Confirm what Healan Centre offers - inferred as an allied health / wellness centre.]' },
  'ablycalm': { notes: '[Add brand details - website, what they do, ICP, offer. Name suggests a wellness / calm / mental-health angle; please confirm.]' },
  'simchat': { notes: '[Add brand details - website, what they do, ICP, offer. Not enough info to auto-fill reliably.]' },
  'owl-psa': { notes: '[Add brand details - website, what they do, ICP, offer. Not enough info to auto-fill reliably.]' },
  'a2z': { notes: '[Add brand details - website, what they do, ICP, offer. Not enough info to auto-fill reliably.]' },
  'ido-ido': { notes: '[Add brand details - website, what they do, ICP, offer. Not enough info to auto-fill reliably.]' },
}

